baseURL = 'https://pshegger.github.io/'
languageCode = 'en-us'
timeZone = 'Europe/Berlin'
title = 'pshegger'
theme = 'hugo-liftoff'

enableRobotsTXT = true
rssLimit = 20
googleAnalytics = 'G-NKBPT9CS94'

defaultContentLanguage = 'en'
enableEmoji = true

[taxonomies]
    tag = 'tags'
    category = 'categories'    
    series = 'series'
    project-type = 'project types'

[related]
  # Default related posts settings
  includeNewer = false
  threshold = 80
  toLower = false

[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
# Remove if not using tags taxonomy
[[related.indices]]
  name = 'tags'
  weight = 80

[frontmatter]
  # Default frontmatter date settings
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = ['lastmod', ':git', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

[caches]
  # Default cache settings
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1

[imaging]
  # Default image processing settings
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 75
  resampleFilter = 'Box'

