[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[[main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    weight = 4

[[main]]
    # Top-level menu entry
    identifier = "explore"
    name = "Explore"
    url = "/categories/"
    weight = 6

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    parent = "explore"
    weight = 6

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    parent = "explore"
    weight = 7

[[main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    parent = "explore"
    weight = 8