name: Build & Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Brew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Hugo
        run: brew install hugo
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          submodules: true
      - name: Checkout & clear old site
        run: |
          cd public
          git checkout master
          rm -rf *
          cd ..
      - name: Build site
        run: hugo -e dev
      - name: Deploy site
        run: |
          cd public
          git config user.name "pshegger"
          git config user.email "pshegger@gmail.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "rebuilding site $(date)"
          git push origin master
